#!/bin/sh
##############################################################################
# DDoS-Defender version 2.1.0 Author: Sunshine Koo <350311204@qq.com>        #
# Modfiy: guzhiqiang, 2012-2-11 11:45:30                                     #
# Blog: http://www.hit008.com , http://www.ywjt.org                          #
##############################################################################
# This program is distributed under the "Artistic License" Agreement         #
# The LICENSE file is located in the same directory as this program. Please  #
# read the LICENSE file before you make copies or distribute this program    #
##############################################################################
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/DDos/sbin
export PATH
CONF_FILE="/usr/local/DDos/conf/ddos.conf"


# Print Header infomation.
header()
{
	echo "DDoS-Defender version 2.1.0"
	echo "Copyright (C) 2010-2012,Sunshine Koo."
	echo
}

# Check if user is root.
if [ $(id -u) != "0" ]; then
    header 
    echo "Error: You must be root to run!"
    exit 1
fi

load_conf()
{
	if [ -f "$CONF_FILE" ] && [ ! "$CONF_FILE" == "" ]; then
		source $CONF_FILE
	else
		header >> $LOGS_FILE
		echo "\$CONF_FILE not found." |tee -a $LOGS_FILE
		exit 1
	fi
}

################################################################################################
flush_exec() {
load_conf
echo "flush_daemon Running OK. $(date +"%y-%m-%d %H:%M:%S")" >> $LOGS_FILE
FLUSH_PID="$PROC_DIR"logs/ddos_flush.SOCK
echo "$$" > $FLUSH_PID

while true
do

#文件存在并不为空
  if [ -f $CROND_LIST ] && [ ! -z "$(cat $CROND_LIST)" ];then
  
    #取得当前时间
     DT=`date +%s`
    #遍历所有条目
    for i in `awk '{print $1}' $CROND_LIST`
    do
      #内容不为空
      if [ -s $CROND_LIST ];then
      #单次最多取出一条,排除重复条目
      GET_KTIME=`grep $i $CROND_LIST|awk '{print $4}'|head -1`
      let "EXPR_KOUT=$DT - $GET_KTIME"
        #判断是否超规定时间
        if [[ $EXPR_KOUT -gt $BAN_PERIOD ]];then
         #iptables里存在条目
         if [ `iptables --list|grep -c $i` -ne 0 ];then
            /sbin/iptables -D INPUT -s $i -j DROP
		    echo "Clean $i OK. $(date +"%y-%m-%d %H:%M:%S")" >> $LOGS_FILE
         fi
          #清除crond_list的当前条目
          sed -i "/$i/d" $CROND_LIST
        fi
      fi 
    done
  fi
  sleep $REXEC_TIME
done
}
flush_exec | tee -a $LOGS_FILE
